builders:
  embedded_env_vars_generator:
    import: "package:embedded_env_vars_generator/builder.dart"
    builder_factories: ["envBuilder"]
    build_extensions: {".dart": [".env.dart"]}
    build_to: source
    auto_apply: root_package
